### ISSUE TITLE
Syntax colors and solarized.vim

### ISSUE THREAD

**Issue by gonzaloserrano** [StanAngeloff/php.vim#37]
Hi again,

I'm using the solarized colorscheme and rainbowcolors for alternating parenthesis colors and so on, and i get something like this:

![screenshot 2015-02-06 18 55 18](https://cloud.githubusercontent.com/assets/349328/6084509/d2161d7a-ae31-11e4-8160-f179b2e61f7a.png)

Which is pretty good IMHO, but i'd like a couple of improvements:

 - colorize the php lib bult-in functions in another color
 - colorize the "dollar" from the var identifiers in another color
 - colorize the method arrow in another color

Since i'm not very good with schemes and syntax files, do you know what would be the best way to accomplish that?

Thanks a lot!

**Comment by StanAngeloff** [comment]
Hey!

> colorize the php lib bult-in functions in another color

You can do this by following the section *Overriding Highlighting* from the README and customising how `phpFunctions` are coloured:

```vim
hi! phpFunctions guifg=#cccccc guibg=NONE gui=NONE
```

> colorize the "dollar" from the var identifiers in another color

You have two options here: if you `let php_var_selector_is_identifier = 1` in your `.vimrc`, the dollar sign will be highlighted in the same colour as the variable name. If you don't specify a value for the variable explicitly, you can customise the colour of the `$` by overriding highlighting for `phpVarSelector`.

> colorize the method arrow in another color

This can be accomplished by overriding highlighting for `phpMemberSelector`. This will affect how `::` is highlighted as well.

---

Here's how your `.vimrc` might look like:

```vim
" Put at the very end of your .vimrc file.
let php_var_selector_is_identifier = 0

function! PhpSyntaxOverride()
  hi! phpFunctions guifg=#ff0000 guibg=NONE gui=NONE
  hi! phpVarSelector guifg=#00ff00 guibg=NONE gui=NONE
  hi! phpMemberSelector guifg=#0000ff guibg=NONE gui=NONE
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
```

NOTE: If you are using terminal Vim, you will have to specify colours using `ctermbg` and `ctermfg` instead of `guifg` and `guibg`.

**Comment by gonzaloserrano** [comment]
Awesome, thanks a lot!

I got something like:

![screenshot 2015-02-09 14 28 48](https://cloud.githubusercontent.com/assets/349328/6107113/0656ae14-b068-11e4-8b5b-d58bae7815c4.png)

Probably i will change the yellow one of the built-in functions one of these days but well.
```
" Put at the very end of your .vimrc file.
let php_var_selector_is_identifier = 0
function! PhpSyntaxOverride()
  hi! def link phpDocTags  phpDefine
  hi! def link phpDocParam phpType
  hi! phpFunctions ctermfg=172 ctermbg=NONE cterm=NONE
  hi! phpVarSelector ctermfg=69 ctermbg=NONE cterm=NONE
  hi! phpMemberSelector ctermfg=136 ctermbg=NONE cterm=NONE
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
```

**Comment by StanAngeloff** [comment]
That looks very appealing!
