### ISSUE TITLE
Docker image on docker hub

### ISSUE THREAD

**Issue by codemedic** [StanAngeloff/php.vim#53]
Please can you build the docker image on docker hub; so that it is readily consumable for docker newbies. Otherwise, it takes ageeees to build.

Thanks

**Comment by StanAngeloff** [comment]
Hi @codemedic,

The image is not meant to be used by newbies. It is used during development to re-generate the `syntax/php.vim` file with the latest version of PHP available. The process updates constants, functions, classes, etc.

There is no value in having the image up on Docker Hub since the `syntax/php.vim` file will always be up-to-date.

Did the README prompt you to build the Docker image yourself as you thought this was needed to get the syntax to work?

**Comment by codemedic** [comment]
Oh, OK. I didn't know that.

Yes, the README did make me wonder if I should run it to bring it upto date (with the PHP version I had on my box; only 5.6).
I wonder if it is worth adding a little note of some kind to say that it is only for development purposes.

Thanks

**Comment by StanAngeloff** [comment]
README has been updated to note using Docker is not needed unless you plan on updating the syntax file yourself.
